server:
  port: 8100
spring:
   profiles:
     active: dev
   application:
     name: changgou_goods
   datasource:
     url: jdbc:mysql://182.92.208.221:3306/changgou_goods?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
     username: root
     password: admin123
     driver-class-name: com.mysql.cj.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
